server:
  port: 8080
spring:
  application:
    name: wholesale-backend
  datasource:
    url: '${DB_URL}'
    username: '${DB_USER}'
    password: '${DB_PASSWORD}'
    driver-class-name: org.postgresql.Driver
jwt:
  secret: wholesale
  refreshToken:
    expirationTime: 360000
  accessToken:
    expirationTime: 360000